### ISSUE TITLE
Github Actions 직접 배포 서버 운영하기

### ISSUE THREAD

**Issue by lns13301** [lns13301/spring-lab#2]
## Actions 생성
Actions 탭에서 new workflow 를 생성한다.
빌드할 툴을 선택한 후 기본 설정에서 변경할 부분을 지정한다.
이 프로젝트의 경우 Gradle 로 빌드를 한다고 가정하면, `gradle.yml` 파일을 설정 후 생성해 준다.
생성하게 되면 자동적으로 최초 빌드가 시작되고 Actions 에서 세부 진행상황을 확인할 수 있다.

Actions 만 사용하면 배포 서버를 자동으로 관리해 준다.

생성할 `gradle.yml` 파일의 예시는 다음과 같다.
```
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: deploy

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: gradlew 권한 변경
      working-directory: ./back/babble
      run: chmod +x gradlew

    - name: 빌드 진행
      working-directory: ./back/babble
      run: ./gradlew clean build

    - name: SCP 명령을 이용해 WAS 서버로 jar 파일 전송
      working-directory: ./back/babble
      run: scp ./build/libs/babble-0.0.1-SNAPSHOT.jar was:/home/ubuntu

    - name: SSH 명령을 통해 WAS 서버 접속 후 jar 파일 실행
      run: ssh was "/home/ubuntu/deploy/deploy.sh"
```

## 직접 배포
Settings -> Actions -> Runners
Add runner
Operating System 과 Architecture 를 설정해 주고, 배포를 진행할 인스턴스에서 Download, Configure 의 명령어를 복사해서 차례대로 입력해준다.
임의로 해당 작업에 이름을 부여할 경우 예를들어 `deploy` 라고 이름을 부여하면 Actions .yml 파일에서 `runs-on: ubuntu-latest` 부분을 `runs-on: deploy` 와 같이 변경하면 된다.

## 서버가 끊겨도 계속 돌아가게 하려면
nohup 관련 명령어로 jar 파일을 실행 시킨다.

## 암호를 관리하는 방법
예시로 사용된 이름 : `deploy`
`deploy.sh` 로 파일을 생성하고 아래 내용을 넣는다.
```
#!/bin/bash
mv /home/ubuntu/babble-0.0.1-SNAPSHOT.jar /home/ubuntu/deploy
sudo pkill -9 -ef babble
nohup java -jar -Dspring.profiles.active=`prod(실행할 profiles)` -Dspring.datasource.password=`암호` /`실행 경로` /dev/null 2>&1 &
```
## Actions Refresh
Actions -> workflow 접속 -> 우측 상단 Re-run jobs

## Reverse Proxy 를 이용하여 Web Socket 을 사용할 때, 웹 소켓 요청을 받으려면 다음과 같은 설정을 해야한다.
`nginx/site-available/default` 경로의 nginx 설정 파일에 아래 내용을 추가해줘야 한다.

```
location /wsapp/ {
    proxy_pass http://wsbackend;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
}
```

## 도커를 사용한다면 다시 빌드하자
위에서 nginx 설정을 건드렸기 때문에 새롭게 빌드를 해야한다.

```
$ sudo docker rm [OPTIONS] CONTAINER [CONTAINER...]
$ docker build -t [생성할 이미지 이름]:[태그] .
$ docker run -d -p 80:80 -p 443:443 --name [컨테이너 이름] [생성할 이미지 이름]:[태그]
```
